package org.akkirrai.hibiki.shared.text

import androidx.compose.runtime.Composable
import hibiki.shared.generated.resources.*
import org.jetbrains.compose.resources.StringResource
import org.jetbrains.compose.resources.pluralStringResource
import org.jetbrains.compose.resources.stringResource

/** Stable keys used by shared UI instead of Android R.string identifiers. */
enum class AppTextKey {
    SharedUiReady,
    AppName,
    Home,
    Catalog,
    Search,
    Library,
    Sources,
    SourcesExtensions,
    SourcesEmptyTitle,
    SourcesSearchFailed,
    SourcesSearchEmptyTitle,
    Profile,
    Settings,
    Featured,
    ContinueWatching,
    ExploreCatalog,
    SearchPlaceholder,
    SearchFilters,
    SearchRetry,
    CatalogSortTitle,
    CatalogSortAlphabetical,
    CatalogSortPopular,
    CatalogSortUpdated,
    FilterUnavailable,
    FilterAllYears,
    FilterFromYear,
    FilterToYear,
    FilterReset,
    FilterApply,
    CatalogError,
    LibraryEmptyTitle,
    LibraryEmptyBody,
    LibraryFilteredEmptyTitle,
    LibrarySearchEmptyTitle,
    LibraryFilteredEmptyBody,
    HomeSearchEmptyTitle,
    HomeSearchEmptyBody,
    HomeSearchLoadMore,
    HomeErrorTitle,
    HomeRecentlyWatched,
    HomeRecentlyAdded,
    HomeContinueTitle,
    HomeContinueEmptyTitle,
    HomeContinueEmptyBody,
    HomeContinueOpenHint,
    HomePersonalEmptyTitle,
    HomePersonalEmptyBody,
    HomeBrowseCatalog,
    SettingsAppearance,
    SettingsTheme,
    SettingsSystemColorScheme,
    SettingsAmoled,
    SettingsPreferences,
    SettingsLanguage,
    SettingsNotifications,
    SettingsNotificationsStatus,
    SettingsNotificationsGranted,
    SettingsNotificationsDenied,
    SettingsPlayer,
    SettingsAutoSkip,
    PlayerSettingsRoot,
    PlayerSettings,
    PlayerSettingsSpeed,
    PlayerSettingsVoiceover,
    PlayerSettingsPlayer,
    PlayerSettingsQuality,
    PlayerSettingsAutoSkip,
    PlayerSettingsAutoPlayNext,
    PlayerSettingsOn,
    PlayerSettingsOff,
    PlayerEpisodeNumber,
    PlayerErrorTitle,
    PlayerRetry,
    PlayerLock,
    PlayerUnlock,
    PlayerPictureInPicture,
    PlayerVideoScaleFit,
    PlayerVideoScaleCrop,
    PlayerVideoScaleStretch,
    PlayerSkip,
    PlayerWatch,
    SettingsExperimental,
    SettingsDiscord,
    DiscordBrowserSignIn,
    DiscordManualToken,
    DiscordInvalidToken,
    DiscordDisconnect,
    DiscordStatusDisabled,
    DiscordStatusSignedOut,
    DiscordStatusChecking,
    DiscordStatusConnecting,
    DiscordStatusConnected,
    DiscordStatusError,
    Cancel,
    Apply,
    SettingsUpdates,
    SettingsCheckUpdates,
    SettingsSupport,
    SettingsExportLogs,
    SettingsAbout,
    SettingsExternalRepositories,
    SettingsExternalSources,
    SettingsExternalSourcesCount,
    SettingsExternalRepositoryUrl,
    SettingsExternalRepositoryUrlHint,
    SettingsExternalRepositoryInvalidUrl,
    SettingsExternalRepositoryOperationFailed,
    SettingsExternalRepositoryAdd,
    SettingsExternalRepositoryRefresh,
    SettingsExternalRepositoryRemove,
    SettingsExternalRepositoryBusy,
    SettingsExternalPackages,
    SettingsExternalPackageInstall,
    SettingsExternalPackageUpdate,
    SettingsExternalPackageInstalled,
    SettingsExternalPackageManage,
    SettingsExternalPackageRollback,
    SettingsExternalPackageUninstall,
    SourcesExternalPackageInfo,
    SourcesExternalPackageVersion,
    SourcesExternalPackageLanguage,
    SourcesExternalRepositories,
    SourcesExternalRepositoriesEmpty,
    SourcesExternalRepositoryAddTitle,
    SourcesExternalRepositoryPaste,
    SourcesExternalRepositoryCopy,
    SourcesExternalRepositorySearch,
    SourcesExternalRepositoryLanguages,
    SourcesExternalRepositoryPackagesEmpty,
    PrototypeNotice,
    PrototypeSubtitle,
    SeeAll,
    SettingsSubtitle,
    SettingsTitle,
    SettingsDescription,
    LanguageSystem,
    LanguageEnglish,
    LanguageRussian,
    ThemeSystem,
    ThemeLight,
    ThemeDark,
    DesktopPreview,
    ProfileLibrary,
    ProfileEpisodes,
    ProfileTabOverview,
    ProfileTabActivity,
    ProfileTabFavorites,
    ProfileName,
    ProfileEdit,
    ProfileSave,
    ProfileChangeAvatar,
    ProfileStatTotal,
    ProfileStatDays,
    ProfileStatTime,
    ProfileRecent,
    ProfileEmptyRecent,
    ProfileEmptyFavorites,
    ProfileAnalyticsWatchTime,
    ProfileAnalyticsTotal,
    ProfileAnalyticsGenres,
    ProfileAnalyticsGenresLabel,
    ProfileAnalyticsWatched,
    ProfileActivity,
    ProfileDateToday,
    ProfileDateYesterday,
    ProfileDateDaysAgo,
    Back,
    Favorite,
    DetailsFavorite,
    Watch,
    WatchSourcesEmptyTitle,
    WatchSourcesEmptyMessage,
    WatchSourcesLoadMore,
    WatchEpisodesEmptyTitle,
    WatchSourceFallback,
    WatchEpisodeHeadline,
    WatchEpisodeHeadlineWatched,
    WatchStatusWatched,
    WatchDownload,
    WatchPause,
    WatchRemoveDownload,
    WatchResume,
    WatchDownloaded,
    WatchStatusQueued,
    WatchStatusDownloading,
    WatchStatusPaused,
    WatchStatusFailed,
    WatchContinue,
    EpisodesShort,
    WatchContinueEpisode,
    WatchContinueEpisodePosition,
    Trailer,
    DetailsTrailer,
    NextEpisodeCountdown,
    NextEpisodeCountdownNumbered,
    NextEpisodeEtaDaysHours,
    NextEpisodeEtaHoursMinutesSeconds,
    NextEpisodeEtaMinutesSeconds,
    Information,
    Status,
    Episodes,
    EpisodesReleased,
    Type,
    ReleaseDate,
    SourceMaterial,
    SourceMaterialManga,
    SourceMaterialManhwa,
    SourceMaterialManhua,
    SourceMaterialLightNovel,
    SourceMaterialWebNovel,
    SourceMaterialVisualNovel,
    SourceMaterialGame,
    SourceMaterialOriginal,
    Studio,
    Genres,
    Related,
    DetailsRelatedTitle,
    Similar,
    Announcement,
    Movie,
    Ongoing,
    Released,
    Unknown,
    LibraryAddTitle,
    LibraryAddSubtitle,
    LibrarySavedNote,
    LibraryRemoveAction,
    LibraryWatching,
    LibraryPlanned,
    LibraryCompleted,
    LibraryDropped,
    LibraryOnHold,
    LibraryFavorite,
    LibrarySaved,
    OnboardingWelcomeTitle,
    OnboardingWelcomeDescription,
    OnboardingGetStarted,
    OnboardingSourceTitle,
    OnboardingSourceDescription,
    OnboardingSourceLanguageRussian,
    OnboardingSourceLanguageEnglish,
    OnboardingSourceLanguagesRussianEnglish,
    OnboardingNotificationsTitle,
    OnboardingNotificationsDescription,
    OnboardingNotificationsAllow,
    OnboardingNotificationsEnabled,
    OnboardingNotificationsDenied,
    OnboardingBack,
    OnboardingNext,
    OnboardingDone,
}

internal val appTextResources: Map<AppTextKey, StringResource> = mapOf(
    AppTextKey.SharedUiReady to Res.string.shared_ui_ready,
    AppTextKey.AppName to Res.string.app_name,
    AppTextKey.Home to Res.string.home,
    AppTextKey.Catalog to Res.string.catalog,
    AppTextKey.Search to Res.string.search,
    AppTextKey.Library to Res.string.library,
    AppTextKey.Sources to Res.string.sources,
    AppTextKey.SourcesExtensions to Res.string.sources_extensions,
    AppTextKey.SourcesEmptyTitle to Res.string.sources_empty_title,
    AppTextKey.SourcesSearchFailed to Res.string.sources_search_failed,
    AppTextKey.SourcesSearchEmptyTitle to Res.string.sources_search_empty_title,
    AppTextKey.Profile to Res.string.profile,
    AppTextKey.Settings to Res.string.settings,
    AppTextKey.Featured to Res.string.featured,
    AppTextKey.ContinueWatching to Res.string.continue_watching,
    AppTextKey.ExploreCatalog to Res.string.explore_catalog,
    AppTextKey.SearchPlaceholder to Res.string.search_placeholder,
    AppTextKey.SearchFilters to Res.string.search_filters,
    AppTextKey.SearchRetry to Res.string.search_retry,
    AppTextKey.CatalogSortTitle to Res.string.catalog_sort_title,
    AppTextKey.CatalogSortAlphabetical to Res.string.catalog_sort_alphabetical,
    AppTextKey.CatalogSortPopular to Res.string.catalog_sort_popular,
    AppTextKey.CatalogSortUpdated to Res.string.catalog_sort_updated,
    AppTextKey.FilterUnavailable to Res.string.filter_unavailable,
    AppTextKey.FilterAllYears to Res.string.filter_all_years,
    AppTextKey.FilterFromYear to Res.string.filter_from_year,
    AppTextKey.FilterToYear to Res.string.filter_to_year,
    AppTextKey.FilterReset to Res.string.filter_reset,
    AppTextKey.FilterApply to Res.string.filter_apply,
    AppTextKey.CatalogError to Res.string.catalog_error,
    AppTextKey.LibraryEmptyTitle to Res.string.library_empty_title,
    AppTextKey.LibraryEmptyBody to Res.string.library_empty_body,
    AppTextKey.LibraryFilteredEmptyTitle to Res.string.library_filtered_empty_title,
    AppTextKey.LibrarySearchEmptyTitle to Res.string.library_search_empty_title,
    AppTextKey.LibraryFilteredEmptyBody to Res.string.library_filtered_empty_body,
    AppTextKey.HomeSearchEmptyTitle to Res.string.home_search_empty_title,
    AppTextKey.HomeSearchEmptyBody to Res.string.home_search_empty_body,
    AppTextKey.HomeSearchLoadMore to Res.string.home_search_load_more,
    AppTextKey.HomeErrorTitle to Res.string.home_error_title,
    AppTextKey.HomeRecentlyWatched to Res.string.home_recently_watched,
    AppTextKey.HomeRecentlyAdded to Res.string.home_recently_added,
    AppTextKey.HomeContinueTitle to Res.string.home_continue_title,
    AppTextKey.HomeContinueEmptyTitle to Res.string.home_continue_empty_title,
    AppTextKey.HomeContinueEmptyBody to Res.string.home_continue_empty_body,
    AppTextKey.HomeContinueOpenHint to Res.string.home_continue_open_hint,
    AppTextKey.HomePersonalEmptyTitle to Res.string.home_personal_empty_title,
    AppTextKey.HomePersonalEmptyBody to Res.string.home_personal_empty_body,
    AppTextKey.HomeBrowseCatalog to Res.string.home_browse_catalog,
    AppTextKey.SettingsAppearance to Res.string.settings_appearance,
    AppTextKey.SettingsTheme to Res.string.settings_theme,
    AppTextKey.SettingsSystemColorScheme to Res.string.settings_system_color_scheme,
    AppTextKey.SettingsAmoled to Res.string.settings_amoled,
    AppTextKey.SettingsPreferences to Res.string.settings_preferences,
    AppTextKey.SettingsLanguage to Res.string.settings_language,
    AppTextKey.SettingsNotifications to Res.string.settings_notifications,
    AppTextKey.SettingsNotificationsStatus to Res.string.settings_notifications_status,
    AppTextKey.SettingsNotificationsGranted to Res.string.settings_notifications_granted,
    AppTextKey.SettingsNotificationsDenied to Res.string.settings_notifications_denied,
    AppTextKey.SettingsPlayer to Res.string.settings_player,
    AppTextKey.SettingsAutoSkip to Res.string.settings_auto_skip,
    AppTextKey.PlayerSettingsRoot to Res.string.player_settings_root,
    AppTextKey.PlayerSettings to Res.string.player_settings,
    AppTextKey.PlayerSettingsSpeed to Res.string.player_settings_speed,
    AppTextKey.PlayerSettingsVoiceover to Res.string.player_settings_voiceover,
    AppTextKey.PlayerSettingsPlayer to Res.string.player_settings_player,
    AppTextKey.PlayerSettingsQuality to Res.string.player_settings_quality,
    AppTextKey.PlayerSettingsAutoSkip to Res.string.player_settings_auto_skip,
    AppTextKey.PlayerSettingsAutoPlayNext to Res.string.player_settings_auto_play_next,
    AppTextKey.PlayerSettingsOn to Res.string.player_settings_on,
    AppTextKey.PlayerSettingsOff to Res.string.player_settings_off,
    AppTextKey.PlayerEpisodeNumber to Res.string.player_episode_number,
    AppTextKey.PlayerErrorTitle to Res.string.player_error_title,
    AppTextKey.PlayerRetry to Res.string.player_retry,
    AppTextKey.PlayerLock to Res.string.player_lock,
    AppTextKey.PlayerUnlock to Res.string.player_unlock,
    AppTextKey.PlayerPictureInPicture to Res.string.player_picture_in_picture,
    AppTextKey.PlayerVideoScaleFit to Res.string.player_video_scale_fit,
    AppTextKey.PlayerVideoScaleCrop to Res.string.player_video_scale_crop,
    AppTextKey.PlayerVideoScaleStretch to Res.string.player_video_scale_stretch,
    AppTextKey.PlayerSkip to Res.string.player_skip,
    AppTextKey.PlayerWatch to Res.string.player_watch,
    AppTextKey.SettingsExperimental to Res.string.settings_experimental,
    AppTextKey.SettingsDiscord to Res.string.settings_discord,
    AppTextKey.DiscordBrowserSignIn to Res.string.discord_browser_sign_in,
    AppTextKey.DiscordManualToken to Res.string.discord_manual_token,
    AppTextKey.DiscordInvalidToken to Res.string.discord_invalid_token,
    AppTextKey.DiscordDisconnect to Res.string.discord_disconnect,
    AppTextKey.DiscordStatusDisabled to Res.string.discord_status_disabled,
    AppTextKey.DiscordStatusSignedOut to Res.string.discord_status_signed_out,
    AppTextKey.DiscordStatusChecking to Res.string.discord_status_checking,
    AppTextKey.DiscordStatusConnecting to Res.string.discord_status_connecting,
    AppTextKey.DiscordStatusConnected to Res.string.discord_status_connected,
    AppTextKey.DiscordStatusError to Res.string.discord_status_error,
    AppTextKey.Cancel to Res.string.cancel,
    AppTextKey.Apply to Res.string.apply,
    AppTextKey.SettingsUpdates to Res.string.settings_updates,
    AppTextKey.SettingsCheckUpdates to Res.string.settings_check_updates,
    AppTextKey.SettingsSupport to Res.string.settings_support,
    AppTextKey.SettingsExportLogs to Res.string.settings_export_logs,
    AppTextKey.SettingsAbout to Res.string.settings_about,
    AppTextKey.SettingsExternalRepositories to Res.string.settings_external_repositories,
    AppTextKey.SettingsExternalSources to Res.string.settings_external_sources,
    AppTextKey.SettingsExternalSourcesCount to Res.string.settings_external_sources_count,
    AppTextKey.SettingsExternalRepositoryUrl to Res.string.settings_external_repository_url,
    AppTextKey.SettingsExternalRepositoryUrlHint to Res.string.settings_external_repository_url_hint,
    AppTextKey.SettingsExternalRepositoryInvalidUrl to Res.string.settings_external_repository_invalid_url,
    AppTextKey.SettingsExternalRepositoryOperationFailed to Res.string.settings_external_repository_operation_failed,
    AppTextKey.SettingsExternalRepositoryAdd to Res.string.settings_external_repository_add,
    AppTextKey.SettingsExternalRepositoryRefresh to Res.string.settings_external_repository_refresh,
    AppTextKey.SettingsExternalRepositoryRemove to Res.string.settings_external_repository_remove,
    AppTextKey.SettingsExternalRepositoryBusy to Res.string.settings_external_repository_busy,
    AppTextKey.SettingsExternalPackages to Res.string.settings_external_packages,
    AppTextKey.SettingsExternalPackageInstall to Res.string.settings_external_package_install,
    AppTextKey.SettingsExternalPackageUpdate to Res.string.settings_external_package_update,
    AppTextKey.SettingsExternalPackageInstalled to Res.string.settings_external_package_installed,
    AppTextKey.SettingsExternalPackageManage to Res.string.settings_external_package_manage,
    AppTextKey.SettingsExternalPackageRollback to Res.string.settings_external_package_rollback,
    AppTextKey.SettingsExternalPackageUninstall to Res.string.settings_external_package_uninstall,
    AppTextKey.SourcesExternalPackageInfo to Res.string.sources_external_package_info,
    AppTextKey.SourcesExternalPackageVersion to Res.string.sources_external_package_version,
    AppTextKey.SourcesExternalPackageLanguage to Res.string.sources_external_package_language,
    AppTextKey.SourcesExternalRepositories to Res.string.sources_external_repositories,
    AppTextKey.SourcesExternalRepositoriesEmpty to Res.string.sources_external_repositories_empty,
    AppTextKey.SourcesExternalRepositoryAddTitle to Res.string.sources_external_repository_add_title,
    AppTextKey.SourcesExternalRepositoryPaste to Res.string.sources_external_repository_paste,
    AppTextKey.SourcesExternalRepositoryCopy to Res.string.sources_external_repository_copy,
    AppTextKey.SourcesExternalRepositorySearch to Res.string.sources_external_repository_search,
    AppTextKey.SourcesExternalRepositoryLanguages to Res.string.sources_external_repository_languages,
    AppTextKey.SourcesExternalRepositoryPackagesEmpty to Res.string.sources_external_repository_packages_empty,
    AppTextKey.PrototypeNotice to Res.string.prototype_notice,
    AppTextKey.PrototypeSubtitle to Res.string.prototype_subtitle,
    AppTextKey.SeeAll to Res.string.see_all,
    AppTextKey.SettingsSubtitle to Res.string.settings_subtitle,
    AppTextKey.SettingsTitle to Res.string.settings_title,
    AppTextKey.SettingsDescription to Res.string.settings_description,
    AppTextKey.LanguageSystem to Res.string.language_system,
    AppTextKey.LanguageEnglish to Res.string.language_english,
    AppTextKey.LanguageRussian to Res.string.language_russian,
    AppTextKey.ThemeSystem to Res.string.theme_system,
    AppTextKey.ThemeLight to Res.string.theme_light,
    AppTextKey.ThemeDark to Res.string.theme_dark,
    AppTextKey.DesktopPreview to Res.string.desktop_preview,
    AppTextKey.ProfileLibrary to Res.string.profile_library,
    AppTextKey.ProfileEpisodes to Res.string.profile_episodes,
    AppTextKey.ProfileTabOverview to Res.string.profile_tab_overview,
    AppTextKey.ProfileTabActivity to Res.string.profile_tab_activity,
    AppTextKey.ProfileTabFavorites to Res.string.profile_tab_favorites,
    AppTextKey.ProfileName to Res.string.profile_name,
    AppTextKey.ProfileEdit to Res.string.profile_edit,
    AppTextKey.ProfileSave to Res.string.profile_save,
    AppTextKey.ProfileChangeAvatar to Res.string.profile_change_avatar,
    AppTextKey.ProfileStatTotal to Res.string.profile_stat_total,
    AppTextKey.ProfileStatDays to Res.string.profile_stat_days,
    AppTextKey.ProfileStatTime to Res.string.profile_stat_time,
    AppTextKey.ProfileRecent to Res.string.profile_recent,
    AppTextKey.ProfileEmptyRecent to Res.string.profile_empty_recent,
    AppTextKey.ProfileEmptyFavorites to Res.string.profile_empty_favorites,
    AppTextKey.ProfileAnalyticsWatchTime to Res.string.profile_analytics_watch_time,
    AppTextKey.ProfileAnalyticsTotal to Res.string.profile_analytics_total,
    AppTextKey.ProfileAnalyticsGenres to Res.string.profile_analytics_genres,
    AppTextKey.ProfileAnalyticsGenresLabel to Res.string.profile_analytics_genres_label,
    AppTextKey.ProfileAnalyticsWatched to Res.string.profile_analytics_watched,
    AppTextKey.ProfileActivity to Res.string.profile_activity,
    AppTextKey.ProfileDateToday to Res.string.profile_date_today,
    AppTextKey.ProfileDateYesterday to Res.string.profile_date_yesterday,
    AppTextKey.ProfileDateDaysAgo to Res.string.profile_date_days_ago,
    AppTextKey.Back to Res.string.back,
    AppTextKey.Favorite to Res.string.favorite,
    AppTextKey.DetailsFavorite to Res.string.details_favorite,
    AppTextKey.Watch to Res.string.watch,
    AppTextKey.WatchSourcesEmptyTitle to Res.string.watch_sources_empty_title,
    AppTextKey.WatchSourcesEmptyMessage to Res.string.watch_sources_empty_message,
    AppTextKey.WatchSourcesLoadMore to Res.string.watch_sources_load_more,
    AppTextKey.WatchEpisodesEmptyTitle to Res.string.watch_episodes_empty_title,
    AppTextKey.WatchSourceFallback to Res.string.watch_source_fallback,
    AppTextKey.WatchEpisodeHeadline to Res.string.watch_episode_headline,
    AppTextKey.WatchEpisodeHeadlineWatched to Res.string.watch_episode_headline_watched,
    AppTextKey.WatchStatusWatched to Res.string.watch_status_watched,
    AppTextKey.WatchDownload to Res.string.watch_download,
    AppTextKey.WatchPause to Res.string.watch_pause,
    AppTextKey.WatchRemoveDownload to Res.string.watch_remove_download,
    AppTextKey.WatchResume to Res.string.watch_resume,
    AppTextKey.WatchDownloaded to Res.string.watch_downloaded,
    AppTextKey.WatchStatusQueued to Res.string.watch_status_queued,
    AppTextKey.WatchStatusDownloading to Res.string.watch_status_downloading,
    AppTextKey.WatchStatusPaused to Res.string.watch_status_paused,
    AppTextKey.WatchStatusFailed to Res.string.watch_status_failed,
    AppTextKey.WatchContinue to Res.string.watch_continue,
    AppTextKey.EpisodesShort to Res.string.episodes_short,
    AppTextKey.WatchContinueEpisode to Res.string.watch_continue_episode,
    AppTextKey.WatchContinueEpisodePosition to Res.string.watch_continue_episode_position,
    AppTextKey.Trailer to Res.string.trailer,
    AppTextKey.DetailsTrailer to Res.string.details_trailer,
    AppTextKey.NextEpisodeCountdown to Res.string.next_episode_countdown,
    AppTextKey.NextEpisodeCountdownNumbered to Res.string.next_episode_countdown_numbered,
    AppTextKey.NextEpisodeEtaDaysHours to Res.string.next_episode_eta_days_hours,
    AppTextKey.NextEpisodeEtaHoursMinutesSeconds to Res.string.next_episode_eta_hours_minutes_seconds,
    AppTextKey.NextEpisodeEtaMinutesSeconds to Res.string.next_episode_eta_minutes_seconds,
    AppTextKey.Information to Res.string.information,
    AppTextKey.Status to Res.string.status,
    AppTextKey.Episodes to Res.string.episodes,
    AppTextKey.EpisodesReleased to Res.string.episodes_released,
    AppTextKey.Type to Res.string.type,
    AppTextKey.ReleaseDate to Res.string.release_date,
    AppTextKey.SourceMaterial to Res.string.source_material,
    AppTextKey.SourceMaterialManga to Res.string.source_material_manga,
    AppTextKey.SourceMaterialManhwa to Res.string.source_material_manhwa,
    AppTextKey.SourceMaterialManhua to Res.string.source_material_manhua,
    AppTextKey.SourceMaterialLightNovel to Res.string.source_material_light_novel,
    AppTextKey.SourceMaterialWebNovel to Res.string.source_material_web_novel,
    AppTextKey.SourceMaterialVisualNovel to Res.string.source_material_visual_novel,
    AppTextKey.SourceMaterialGame to Res.string.source_material_game,
    AppTextKey.SourceMaterialOriginal to Res.string.source_material_original,
    AppTextKey.Studio to Res.string.studio,
    AppTextKey.Genres to Res.string.genres,
    AppTextKey.Related to Res.string.related,
    AppTextKey.DetailsRelatedTitle to Res.string.details_related_title,
    AppTextKey.Similar to Res.string.similar,
    AppTextKey.Announcement to Res.string.announcement,
    AppTextKey.Movie to Res.string.movie,
    AppTextKey.Ongoing to Res.string.ongoing,
    AppTextKey.Released to Res.string.released,
    AppTextKey.Unknown to Res.string.unknown,
    AppTextKey.LibraryAddTitle to Res.string.library_add_title,
    AppTextKey.LibraryAddSubtitle to Res.string.library_add_subtitle,
    AppTextKey.LibrarySavedNote to Res.string.library_saved_note,
    AppTextKey.LibraryRemoveAction to Res.string.library_remove_action,
    AppTextKey.LibraryWatching to Res.string.library_watching,
    AppTextKey.LibraryPlanned to Res.string.library_planned,
    AppTextKey.LibraryCompleted to Res.string.library_completed,
    AppTextKey.LibraryDropped to Res.string.library_dropped,
    AppTextKey.LibraryOnHold to Res.string.library_on_hold,
    AppTextKey.LibraryFavorite to Res.string.library_favorite,
    AppTextKey.LibrarySaved to Res.string.library_saved,
    AppTextKey.OnboardingWelcomeTitle to Res.string.onboarding_welcome_title,
    AppTextKey.OnboardingWelcomeDescription to Res.string.onboarding_welcome_description,
    AppTextKey.OnboardingGetStarted to Res.string.onboarding_get_started,
    AppTextKey.OnboardingSourceTitle to Res.string.onboarding_source_title,
    AppTextKey.OnboardingSourceDescription to Res.string.onboarding_source_description,
    AppTextKey.OnboardingSourceLanguageRussian to Res.string.onboarding_source_language_russian,
    AppTextKey.OnboardingSourceLanguageEnglish to Res.string.onboarding_source_language_english,
    AppTextKey.OnboardingSourceLanguagesRussianEnglish to Res.string.onboarding_source_languages_russian_english,
    AppTextKey.OnboardingNotificationsTitle to Res.string.onboarding_notifications_title,
    AppTextKey.OnboardingNotificationsDescription to Res.string.onboarding_notifications_description,
    AppTextKey.OnboardingNotificationsAllow to Res.string.onboarding_notifications_allow,
    AppTextKey.OnboardingNotificationsEnabled to Res.string.onboarding_notifications_enabled,
    AppTextKey.OnboardingNotificationsDenied to Res.string.onboarding_notifications_denied,
    AppTextKey.OnboardingBack to Res.string.onboarding_back,
    AppTextKey.OnboardingNext to Res.string.onboarding_next,
    AppTextKey.OnboardingDone to Res.string.onboarding_done,
 )

internal fun AppTextKey.resource(): StringResource =
    checkNotNull(appTextResources[this]) { "Missing resource for $this" }

@Composable
fun appText(key: AppTextKey): String = stringResource(key.resource())

@Composable
fun appSearchResultsCount(count: Int): String =
    pluralStringResource(Res.plurals.search_results_count, count, count)
