package org.akkirrai.hibiki.text

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.pluralStringResource
import androidx.compose.ui.res.stringResource
import org.akkirrai.hibiki.R

/** Stable keys used by shared UI instead of Android R.string identifiers. */
enum class AppTextKey {
    SharedUiReady,
    AppName,
    Home,
    Catalog,
    Search,
    Library,
    Sources,
    SourcesExtensions,
    SourcesEmptyTitle,
    SourcesSearchFailed,
    SourcesSearchEmptyTitle,
    Profile,
    Settings,
    Featured,
    ContinueWatching,
    ExploreCatalog,
    SearchPlaceholder,
    SearchFilters,
    SearchRetry,
    CatalogSortTitle,
    CatalogSortAlphabetical,
    CatalogSortPopular,
    CatalogSortUpdated,
    FilterUnavailable,
    FilterAllYears,
    FilterFromYear,
    FilterToYear,
    FilterReset,
    FilterApply,
    CatalogError,
    LibraryEmptyTitle,
    LibraryEmptyBody,
    LibraryFilteredEmptyTitle,
    LibrarySearchEmptyTitle,
    LibraryFilteredEmptyBody,
    HomeSearchEmptyTitle,
    HomeSearchEmptyBody,
    HomeSearchLoadMore,
    HomeErrorTitle,
    HomeRecentlyWatched,
    HomeRecentlyAdded,
    HomeContinueTitle,
    HomeContinueEmptyTitle,
    HomeContinueEmptyBody,
    HomeContinueOpenHint,
    HomePersonalEmptyTitle,
    HomePersonalEmptyBody,
    HomeBrowseCatalog,
    SettingsAppearance,
    SettingsTheme,
    SettingsSystemColorScheme,
    SettingsAmoled,
    SettingsPreferences,
    SettingsLanguage,
    SettingsNotifications,
    SettingsNotificationsStatus,
    SettingsNotificationsGranted,
    SettingsNotificationsDenied,
    SettingsPlayer,
    SettingsAutoSkip,
    PlayerSettingsRoot,
    PlayerSettings,
    PlayerSettingsSpeed,
    PlayerSettingsVoiceover,
    PlayerSettingsPlayer,
    PlayerSettingsQuality,
    PlayerSettingsAutoSkip,
    PlayerSettingsAutoPlayNext,
    PlayerSettingsOn,
    PlayerSettingsOff,
    PlayerEpisodeNumber,
    PlayerErrorTitle,
    PlayerRetry,
    PlayerLock,
    PlayerUnlock,
    PlayerPictureInPicture,
    PlayerVideoScaleFit,
    PlayerVideoScaleCrop,
    PlayerVideoScaleStretch,
    PlayerSkip,
    PlayerWatch,
    SettingsExperimental,
    SettingsDiscord,
    DiscordBrowserSignIn,
    DiscordManualToken,
    DiscordInvalidToken,
    DiscordDisconnect,
    DiscordStatusDisabled,
    DiscordStatusSignedOut,
    DiscordStatusChecking,
    DiscordStatusConnecting,
    DiscordStatusConnected,
    DiscordStatusError,
    Cancel,
    Apply,
    SettingsUpdates,
    SettingsCheckUpdates,
    SettingsSupport,
    SettingsExportLogs,
    SettingsAbout,
    SettingsExternalRepositories,
    SettingsExternalSources,
    SettingsExternalSourcesCount,
    SettingsExternalRepositoryUrl,
    SettingsExternalRepositoryUrlHint,
    SettingsExternalRepositoryInvalidUrl,
    SettingsExternalRepositoryOperationFailed,
    SettingsExternalRepositoryAdd,
    SettingsExternalRepositoryRefresh,
    SettingsExternalRepositoryRemove,
    SettingsExternalRepositoryBusy,
    SettingsExternalPackages,
    SettingsExternalPackageInstall,
    SettingsExternalPackageUpdate,
    SettingsExternalPackageInstalled,
    SettingsExternalPackageManage,
    SettingsExternalPackageUninstall,
    SourcesExternalPackageInfo,
    SourcesExternalPackageVersion,
    SourcesExternalPackageLanguage,
    SourcesExternalRepositories,
    SourcesExternalRepositoriesEmpty,
    SourcesExternalRepositoryAddTitle,
    SourcesExternalRepositoryPaste,
    SourcesExternalRepositoryCopy,
    SourcesExternalRepositorySearch,
    SourcesExternalRepositoryLanguages,
    SourcesExternalRepositoryPackagesEmpty,
    PrototypeNotice,
    PrototypeSubtitle,
    SeeAll,
    SettingsSubtitle,
    SettingsTitle,
    SettingsDescription,
    LanguageSystem,
    LanguageEnglish,
    LanguageRussian,
    ThemeSystem,
    ThemeLight,
    ThemeDark,
    DesktopPreview,
    ProfileLibrary,
    ProfileEpisodes,
    ProfileTabOverview,
    ProfileTabActivity,
    ProfileTabFavorites,
    ProfileName,
    ProfileEdit,
    ProfileSave,
    ProfileChangeAvatar,
    ProfileStatTotal,
    ProfileStatDays,
    ProfileStatTime,
    ProfileRecent,
    ProfileEmptyRecent,
    ProfileEmptyFavorites,
    ProfileAnalyticsWatchTime,
    ProfileAnalyticsTotal,
    ProfileAnalyticsGenres,
    ProfileAnalyticsGenresLabel,
    ProfileAnalyticsWatched,
    ProfileActivity,
    ProfileDateToday,
    ProfileDateYesterday,
    ProfileDateDaysAgo,
    Back,
    Favorite,
    DetailsFavorite,
    Watch,
    WatchSourcesEmptyTitle,
    WatchSourcesEmptyMessage,
    WatchSourcesLoadMore,
    WatchEpisodesEmptyTitle,
    WatchSourceFallback,
    WatchEpisodeHeadline,
    WatchEpisodeHeadlineWatched,
    WatchStatusWatched,
    WatchDownload,
    WatchPause,
    WatchRemoveDownload,
    WatchResume,
    WatchDownloaded,
    WatchStatusQueued,
    WatchStatusDownloading,
    WatchStatusPaused,
    WatchStatusFailed,
    WatchContinue,
    EpisodesShort,
    WatchContinueEpisode,
    WatchContinueEpisodePosition,
    Trailer,
    DetailsTrailer,
    NextEpisodeCountdown,
    NextEpisodeCountdownNumbered,
    NextEpisodeEtaDaysHours,
    NextEpisodeEtaHoursMinutesSeconds,
    NextEpisodeEtaMinutesSeconds,
    EpisodeReminderSchedule,
    EpisodeReminderScheduled,
    Information,
    Status,
    Episodes,
    EpisodesReleased,
    Type,
    ReleaseDate,
    SourceMaterial,
    SourceMaterialManga,
    SourceMaterialManhwa,
    SourceMaterialManhua,
    SourceMaterialLightNovel,
    SourceMaterialWebNovel,
    SourceMaterialVisualNovel,
    SourceMaterialGame,
    SourceMaterialOriginal,
    Studio,
    Genres,
    Related,
    DetailsRelatedTitle,
    Similar,
    Announcement,
    Movie,
    Ongoing,
    Released,
    Unknown,
    LibraryAddTitle,
    LibraryAddSubtitle,
    LibrarySavedNote,
    LibraryRemoveAction,
    LibraryWatching,
    LibraryPlanned,
    LibraryCompleted,
    LibraryDropped,
    LibraryOnHold,
    LibraryFavorite,
    LibrarySaved,
    OnboardingWelcomeTitle,
    OnboardingWelcomeDescription,
    OnboardingGetStarted,
    OnboardingSourceTitle,
    OnboardingSourceDescription,
    OnboardingSourceLanguageRussian,
    OnboardingSourceLanguageEnglish,
    OnboardingSourceLanguagesRussianEnglish,
    OnboardingNotificationsTitle,
    OnboardingNotificationsDescription,
    OnboardingNotificationsAllow,
    OnboardingNotificationsEnabled,
    OnboardingNotificationsDenied,
    OnboardingBack,
    OnboardingNext,
    OnboardingDone,
}

internal val appTextResources: Map<AppTextKey, Int> = mapOf(
    AppTextKey.SharedUiReady to R.string.shared_ui_ready,
    AppTextKey.AppName to R.string.app_name,
    AppTextKey.Home to R.string.home,
    AppTextKey.Catalog to R.string.catalog,
    AppTextKey.Search to R.string.search,
    AppTextKey.Library to R.string.library,
    AppTextKey.Sources to R.string.sources,
    AppTextKey.SourcesExtensions to R.string.sources_extensions,
    AppTextKey.SourcesEmptyTitle to R.string.sources_empty_title,
    AppTextKey.SourcesSearchFailed to R.string.sources_search_failed,
    AppTextKey.SourcesSearchEmptyTitle to R.string.sources_search_empty_title,
    AppTextKey.Profile to R.string.profile,
    AppTextKey.Settings to R.string.settings,
    AppTextKey.Featured to R.string.featured,
    AppTextKey.ContinueWatching to R.string.continue_watching,
    AppTextKey.ExploreCatalog to R.string.explore_catalog,
    AppTextKey.SearchPlaceholder to R.string.search_placeholder,
    AppTextKey.SearchFilters to R.string.search_filters,
    AppTextKey.SearchRetry to R.string.search_retry,
    AppTextKey.CatalogSortTitle to R.string.catalog_sort_title,
    AppTextKey.CatalogSortAlphabetical to R.string.catalog_sort_alphabetical,
    AppTextKey.CatalogSortPopular to R.string.catalog_sort_popular,
    AppTextKey.CatalogSortUpdated to R.string.catalog_sort_updated,
    AppTextKey.FilterUnavailable to R.string.filter_unavailable,
    AppTextKey.FilterAllYears to R.string.filter_all_years,
    AppTextKey.FilterFromYear to R.string.filter_from_year,
    AppTextKey.FilterToYear to R.string.filter_to_year,
    AppTextKey.FilterReset to R.string.filter_reset,
    AppTextKey.FilterApply to R.string.filter_apply,
    AppTextKey.CatalogError to R.string.catalog_error,
    AppTextKey.LibraryEmptyTitle to R.string.library_empty_title,
    AppTextKey.LibraryEmptyBody to R.string.library_empty_body,
    AppTextKey.LibraryFilteredEmptyTitle to R.string.library_filtered_empty_title,
    AppTextKey.LibrarySearchEmptyTitle to R.string.library_search_empty_title,
    AppTextKey.LibraryFilteredEmptyBody to R.string.library_filtered_empty_body,
    AppTextKey.HomeSearchEmptyTitle to R.string.home_search_empty_title,
    AppTextKey.HomeSearchEmptyBody to R.string.home_search_empty_body,
    AppTextKey.HomeSearchLoadMore to R.string.home_search_load_more,
    AppTextKey.HomeErrorTitle to R.string.home_error_title,
    AppTextKey.HomeRecentlyWatched to R.string.home_recently_watched,
    AppTextKey.HomeRecentlyAdded to R.string.home_recently_added,
    AppTextKey.HomeContinueTitle to R.string.home_continue_title,
    AppTextKey.HomeContinueEmptyTitle to R.string.home_continue_empty_title,
    AppTextKey.HomeContinueEmptyBody to R.string.home_continue_empty_body,
    AppTextKey.HomeContinueOpenHint to R.string.home_continue_open_hint,
    AppTextKey.HomePersonalEmptyTitle to R.string.home_personal_empty_title,
    AppTextKey.HomePersonalEmptyBody to R.string.home_personal_empty_body,
    AppTextKey.HomeBrowseCatalog to R.string.home_browse_catalog,
    AppTextKey.SettingsAppearance to R.string.settings_appearance,
    AppTextKey.SettingsTheme to R.string.settings_theme,
    AppTextKey.SettingsSystemColorScheme to R.string.settings_system_color_scheme,
    AppTextKey.SettingsAmoled to R.string.settings_amoled,
    AppTextKey.SettingsPreferences to R.string.settings_preferences,
    AppTextKey.SettingsLanguage to R.string.settings_language,
    AppTextKey.SettingsNotifications to R.string.settings_notifications,
    AppTextKey.SettingsNotificationsStatus to R.string.settings_notifications_status,
    AppTextKey.SettingsNotificationsGranted to R.string.settings_notifications_granted,
    AppTextKey.SettingsNotificationsDenied to R.string.settings_notifications_denied,
    AppTextKey.SettingsPlayer to R.string.settings_player,
    AppTextKey.SettingsAutoSkip to R.string.settings_auto_skip,
    AppTextKey.PlayerSettingsRoot to R.string.player_settings_root,
    AppTextKey.PlayerSettings to R.string.player_settings,
    AppTextKey.PlayerSettingsSpeed to R.string.player_settings_speed,
    AppTextKey.PlayerSettingsVoiceover to R.string.player_settings_voiceover,
    AppTextKey.PlayerSettingsPlayer to R.string.player_settings_player,
    AppTextKey.PlayerSettingsQuality to R.string.player_settings_quality,
    AppTextKey.PlayerSettingsAutoSkip to R.string.player_settings_auto_skip,
    AppTextKey.PlayerSettingsAutoPlayNext to R.string.player_settings_auto_play_next,
    AppTextKey.PlayerSettingsOn to R.string.player_settings_on,
    AppTextKey.PlayerSettingsOff to R.string.player_settings_off,
    AppTextKey.PlayerEpisodeNumber to R.string.player_episode_number,
    AppTextKey.PlayerErrorTitle to R.string.player_error_title,
    AppTextKey.PlayerRetry to R.string.player_retry,
    AppTextKey.PlayerLock to R.string.player_lock,
    AppTextKey.PlayerUnlock to R.string.player_unlock,
    AppTextKey.PlayerPictureInPicture to R.string.player_picture_in_picture,
    AppTextKey.PlayerVideoScaleFit to R.string.player_video_scale_fit,
    AppTextKey.PlayerVideoScaleCrop to R.string.player_video_scale_crop,
    AppTextKey.PlayerVideoScaleStretch to R.string.player_video_scale_stretch,
    AppTextKey.PlayerSkip to R.string.player_skip,
    AppTextKey.PlayerWatch to R.string.player_watch,
    AppTextKey.SettingsExperimental to R.string.settings_experimental,
    AppTextKey.SettingsDiscord to R.string.settings_discord,
    AppTextKey.DiscordBrowserSignIn to R.string.discord_browser_sign_in,
    AppTextKey.DiscordManualToken to R.string.discord_manual_token,
    AppTextKey.DiscordInvalidToken to R.string.discord_invalid_token,
    AppTextKey.DiscordDisconnect to R.string.discord_disconnect,
    AppTextKey.DiscordStatusDisabled to R.string.discord_status_disabled,
    AppTextKey.DiscordStatusSignedOut to R.string.discord_status_signed_out,
    AppTextKey.DiscordStatusChecking to R.string.discord_status_checking,
    AppTextKey.DiscordStatusConnecting to R.string.discord_status_connecting,
    AppTextKey.DiscordStatusConnected to R.string.discord_status_connected,
    AppTextKey.DiscordStatusError to R.string.discord_status_error,
    AppTextKey.Cancel to R.string.cancel,
    AppTextKey.Apply to R.string.apply,
    AppTextKey.SettingsUpdates to R.string.settings_updates,
    AppTextKey.SettingsCheckUpdates to R.string.settings_check_updates,
    AppTextKey.SettingsSupport to R.string.settings_support,
    AppTextKey.SettingsExportLogs to R.string.settings_export_logs,
    AppTextKey.SettingsAbout to R.string.settings_about,
    AppTextKey.SettingsExternalRepositories to R.string.settings_external_repositories,
    AppTextKey.SettingsExternalSources to R.string.settings_external_sources,
    AppTextKey.SettingsExternalSourcesCount to R.string.settings_external_sources_count,
    AppTextKey.SettingsExternalRepositoryUrl to R.string.settings_external_repository_url,
    AppTextKey.SettingsExternalRepositoryUrlHint to R.string.settings_external_repository_url_hint,
    AppTextKey.SettingsExternalRepositoryInvalidUrl to R.string.settings_external_repository_invalid_url,
    AppTextKey.SettingsExternalRepositoryOperationFailed to R.string.settings_external_repository_operation_failed,
    AppTextKey.SettingsExternalRepositoryAdd to R.string.settings_external_repository_add,
    AppTextKey.SettingsExternalRepositoryRefresh to R.string.settings_external_repository_refresh,
    AppTextKey.SettingsExternalRepositoryRemove to R.string.settings_external_repository_remove,
    AppTextKey.SettingsExternalRepositoryBusy to R.string.settings_external_repository_busy,
    AppTextKey.SettingsExternalPackages to R.string.settings_external_packages,
    AppTextKey.SettingsExternalPackageInstall to R.string.settings_external_package_install,
    AppTextKey.SettingsExternalPackageUpdate to R.string.settings_external_package_update,
    AppTextKey.SettingsExternalPackageInstalled to R.string.settings_external_package_installed,
    AppTextKey.SettingsExternalPackageManage to R.string.settings_external_package_manage,
    AppTextKey.SettingsExternalPackageUninstall to R.string.settings_external_package_uninstall,
    AppTextKey.SourcesExternalPackageInfo to R.string.sources_external_package_info,
    AppTextKey.SourcesExternalPackageVersion to R.string.sources_external_package_version,
    AppTextKey.SourcesExternalPackageLanguage to R.string.sources_external_package_language,
    AppTextKey.SourcesExternalRepositories to R.string.sources_external_repositories,
    AppTextKey.SourcesExternalRepositoriesEmpty to R.string.sources_external_repositories_empty,
    AppTextKey.SourcesExternalRepositoryAddTitle to R.string.sources_external_repository_add_title,
    AppTextKey.SourcesExternalRepositoryPaste to R.string.sources_external_repository_paste,
    AppTextKey.SourcesExternalRepositoryCopy to R.string.sources_external_repository_copy,
    AppTextKey.SourcesExternalRepositorySearch to R.string.sources_external_repository_search,
    AppTextKey.SourcesExternalRepositoryLanguages to R.string.sources_external_repository_languages,
    AppTextKey.SourcesExternalRepositoryPackagesEmpty to R.string.sources_external_repository_packages_empty,
    AppTextKey.PrototypeNotice to R.string.prototype_notice,
    AppTextKey.PrototypeSubtitle to R.string.prototype_subtitle,
    AppTextKey.SeeAll to R.string.see_all,
    AppTextKey.SettingsSubtitle to R.string.settings_subtitle,
    AppTextKey.SettingsTitle to R.string.settings_title,
    AppTextKey.SettingsDescription to R.string.settings_description,
    AppTextKey.LanguageSystem to R.string.language_system,
    AppTextKey.LanguageEnglish to R.string.language_english,
    AppTextKey.LanguageRussian to R.string.language_russian,
    AppTextKey.ThemeSystem to R.string.theme_system,
    AppTextKey.ThemeLight to R.string.theme_light,
    AppTextKey.ThemeDark to R.string.theme_dark,
    AppTextKey.DesktopPreview to R.string.desktop_preview,
    AppTextKey.ProfileLibrary to R.string.profile_library,
    AppTextKey.ProfileEpisodes to R.string.profile_episodes,
    AppTextKey.ProfileTabOverview to R.string.profile_tab_overview,
    AppTextKey.ProfileTabActivity to R.string.profile_tab_activity,
    AppTextKey.ProfileTabFavorites to R.string.profile_tab_favorites,
    AppTextKey.ProfileName to R.string.profile_name,
    AppTextKey.ProfileEdit to R.string.profile_edit,
    AppTextKey.ProfileSave to R.string.profile_save,
    AppTextKey.ProfileChangeAvatar to R.string.profile_change_avatar,
    AppTextKey.ProfileStatTotal to R.string.profile_stat_total,
    AppTextKey.ProfileStatDays to R.string.profile_stat_days,
    AppTextKey.ProfileStatTime to R.string.profile_stat_time,
    AppTextKey.ProfileRecent to R.string.profile_recent,
    AppTextKey.ProfileEmptyRecent to R.string.profile_empty_recent,
    AppTextKey.ProfileEmptyFavorites to R.string.profile_empty_favorites,
    AppTextKey.ProfileAnalyticsWatchTime to R.string.profile_analytics_watch_time,
    AppTextKey.ProfileAnalyticsTotal to R.string.profile_analytics_total,
    AppTextKey.ProfileAnalyticsGenres to R.string.profile_analytics_genres,
    AppTextKey.ProfileAnalyticsGenresLabel to R.string.profile_analytics_genres_label,
    AppTextKey.ProfileAnalyticsWatched to R.string.profile_analytics_watched,
    AppTextKey.ProfileActivity to R.string.profile_activity,
    AppTextKey.ProfileDateToday to R.string.profile_date_today,
    AppTextKey.ProfileDateYesterday to R.string.profile_date_yesterday,
    AppTextKey.ProfileDateDaysAgo to R.string.profile_date_days_ago,
    AppTextKey.Back to R.string.back,
    AppTextKey.Favorite to R.string.favorite,
    AppTextKey.DetailsFavorite to R.string.details_favorite,
    AppTextKey.Watch to R.string.watch,
    AppTextKey.WatchSourcesEmptyTitle to R.string.watch_sources_empty_title,
    AppTextKey.WatchSourcesEmptyMessage to R.string.watch_sources_empty_message,
    AppTextKey.WatchSourcesLoadMore to R.string.watch_sources_load_more,
    AppTextKey.WatchEpisodesEmptyTitle to R.string.watch_episodes_empty_title,
    AppTextKey.WatchSourceFallback to R.string.watch_source_fallback,
    AppTextKey.WatchEpisodeHeadline to R.string.watch_episode_headline,
    AppTextKey.WatchEpisodeHeadlineWatched to R.string.watch_episode_headline_watched,
    AppTextKey.WatchStatusWatched to R.string.watch_status_watched,
    AppTextKey.WatchDownload to R.string.watch_download,
    AppTextKey.WatchPause to R.string.watch_pause,
    AppTextKey.WatchRemoveDownload to R.string.watch_remove_download,
    AppTextKey.WatchResume to R.string.watch_resume,
    AppTextKey.WatchDownloaded to R.string.watch_downloaded,
    AppTextKey.WatchStatusQueued to R.string.watch_status_queued,
    AppTextKey.WatchStatusDownloading to R.string.watch_status_downloading,
    AppTextKey.WatchStatusPaused to R.string.watch_status_paused,
    AppTextKey.WatchStatusFailed to R.string.watch_status_failed,
    AppTextKey.WatchContinue to R.string.watch_continue,
    AppTextKey.EpisodesShort to R.string.episodes_short,
    AppTextKey.WatchContinueEpisode to R.string.watch_continue_episode,
    AppTextKey.WatchContinueEpisodePosition to R.string.watch_continue_episode_position,
    AppTextKey.Trailer to R.string.trailer,
    AppTextKey.DetailsTrailer to R.string.details_trailer,
    AppTextKey.NextEpisodeCountdown to R.string.next_episode_countdown,
    AppTextKey.NextEpisodeCountdownNumbered to R.string.next_episode_countdown_numbered,
    AppTextKey.NextEpisodeEtaDaysHours to R.string.next_episode_eta_days_hours,
    AppTextKey.NextEpisodeEtaHoursMinutesSeconds to R.string.next_episode_eta_hours_minutes_seconds,
    AppTextKey.NextEpisodeEtaMinutesSeconds to R.string.next_episode_eta_minutes_seconds,
    AppTextKey.EpisodeReminderSchedule to R.string.episode_reminder_schedule,
    AppTextKey.EpisodeReminderScheduled to R.string.episode_reminder_scheduled,
    AppTextKey.Information to R.string.information,
    AppTextKey.Status to R.string.status,
    AppTextKey.Episodes to R.string.episodes,
    AppTextKey.EpisodesReleased to R.string.episodes_released,
    AppTextKey.Type to R.string.type,
    AppTextKey.ReleaseDate to R.string.release_date,
    AppTextKey.SourceMaterial to R.string.source_material,
    AppTextKey.SourceMaterialManga to R.string.source_material_manga,
    AppTextKey.SourceMaterialManhwa to R.string.source_material_manhwa,
    AppTextKey.SourceMaterialManhua to R.string.source_material_manhua,
    AppTextKey.SourceMaterialLightNovel to R.string.source_material_light_novel,
    AppTextKey.SourceMaterialWebNovel to R.string.source_material_web_novel,
    AppTextKey.SourceMaterialVisualNovel to R.string.source_material_visual_novel,
    AppTextKey.SourceMaterialGame to R.string.source_material_game,
    AppTextKey.SourceMaterialOriginal to R.string.source_material_original,
    AppTextKey.Studio to R.string.studio,
    AppTextKey.Genres to R.string.genres,
    AppTextKey.Related to R.string.related,
    AppTextKey.DetailsRelatedTitle to R.string.details_related_title,
    AppTextKey.Similar to R.string.similar,
    AppTextKey.Announcement to R.string.announcement,
    AppTextKey.Movie to R.string.movie,
    AppTextKey.Ongoing to R.string.ongoing,
    AppTextKey.Released to R.string.released,
    AppTextKey.Unknown to R.string.unknown,
    AppTextKey.LibraryAddTitle to R.string.library_add_title,
    AppTextKey.LibraryAddSubtitle to R.string.library_add_subtitle,
    AppTextKey.LibrarySavedNote to R.string.library_saved_note,
    AppTextKey.LibraryRemoveAction to R.string.library_remove_action,
    AppTextKey.LibraryWatching to R.string.library_watching,
    AppTextKey.LibraryPlanned to R.string.library_planned,
    AppTextKey.LibraryCompleted to R.string.library_completed,
    AppTextKey.LibraryDropped to R.string.library_dropped,
    AppTextKey.LibraryOnHold to R.string.library_on_hold,
    AppTextKey.LibraryFavorite to R.string.library_favorite,
    AppTextKey.LibrarySaved to R.string.library_saved,
    AppTextKey.OnboardingWelcomeTitle to R.string.onboarding_welcome_title,
    AppTextKey.OnboardingWelcomeDescription to R.string.onboarding_welcome_description,
    AppTextKey.OnboardingGetStarted to R.string.onboarding_get_started,
    AppTextKey.OnboardingSourceTitle to R.string.onboarding_source_title,
    AppTextKey.OnboardingSourceDescription to R.string.onboarding_source_description,
    AppTextKey.OnboardingSourceLanguageRussian to R.string.onboarding_source_language_russian,
    AppTextKey.OnboardingSourceLanguageEnglish to R.string.onboarding_source_language_english,
    AppTextKey.OnboardingSourceLanguagesRussianEnglish to R.string.onboarding_source_languages_russian_english,
    AppTextKey.OnboardingNotificationsTitle to R.string.onboarding_notifications_title,
    AppTextKey.OnboardingNotificationsDescription to R.string.onboarding_notifications_description,
    AppTextKey.OnboardingNotificationsAllow to R.string.onboarding_notifications_allow,
    AppTextKey.OnboardingNotificationsEnabled to R.string.onboarding_notifications_enabled,
    AppTextKey.OnboardingNotificationsDenied to R.string.onboarding_notifications_denied,
    AppTextKey.OnboardingBack to R.string.onboarding_back,
    AppTextKey.OnboardingNext to R.string.onboarding_next,
    AppTextKey.OnboardingDone to R.string.onboarding_done,
 )

internal fun AppTextKey.resource(): Int =
    checkNotNull(appTextResources[this]) { "Missing resource for $this" }

@Composable
fun appText(key: AppTextKey): String = stringResource(key.resource())

@Composable
fun appSearchResultsCount(count: Int): String =
    pluralStringResource(R.plurals.search_results_count, count, count)
