package org.akkirrai.beakokit.source

import org.akkirrai.beakokit.api.SourceCatalog
import org.akkirrai.beakokit.api.SourceEntry
import org.akkirrai.beakokit.api.SourceFactory
import org.akkirrai.beakokit.source.aniliberty.AniLibertySource
import org.akkirrai.beakokit.source.yummy.YummyAnimeSource

/** Hand-written for now; this exact catalog shape can later be generated by KSP. */
object BuiltInSources {
    val YUMMY_ANIME_ID = YummyAnimeSource.INFO.id
    val ANI_LIBERTY_ID = AniLibertySource.INFO.id

    val catalog = SourceCatalog(
        listOf(
            SourceEntry(
                info = YummyAnimeSource.INFO,
                factory = SourceFactory(::YummyAnimeSource),
            ),
            SourceEntry(
                info = AniLibertySource.INFO,
                factory = SourceFactory(::AniLibertySource),
            ),
        ),
    )
}
