package org.akkirrai.beakokit.source

import org.akkirrai.beakokit.api.SourceCatalog
import org.akkirrai.beakokit.generated.GeneratedSourceCatalog

/** Hand-written for now; this exact catalog shape can later be generated by KSP. */
object BuiltInSources {
    val YUMMY_ANIME_ID = GeneratedSourceCatalog.YUMMY_ANIME_ID
    val ANI_LIBERTY_ID = GeneratedSourceCatalog.ANI_LIBERTY_ID

    val catalog: SourceCatalog = GeneratedSourceCatalog.catalog
}
